apiVersion: v1
kind: Secret
metadata:
  name: hi-events-secrets
type: Opaque
stringData:
  APP_KEY: base64:3Dk+bq59pjSWyH9FsouoU3piK5LbYXlBg5IdJ6VRLfo=
  JWT_SECRET: zB6xrJI3Ap9zGBXb384UUa7YomZ0ehoD9R5OkikWnYY=
