apiVersion: v1
kind: Service
metadata:
  name: hi-events
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: hi-events
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
